// <auto-generated />
using Breshop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Breshop.Migrations
{
    [DbContext(typeof(BreshopContext))]
    [Migration("20230102200432_AdicionadoNovasColunas")]
    partial class AdicionadoNovasColunas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Breshop.Models.Carrinho", b =>
                {
                    b.Property<int>("IdCarrinho")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CD_CARRINHO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CarrinhoDisponivel")
                        .HasColumnName("IC_CARRINHO_DISPONIVEL");

                    b.Property<int>("IdProdutoCarrinho")
                        .HasColumnName("CD_CARRINHO_PRODUTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdCarrinho");

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("Breshop.Models.CarrinhoProduto", b =>
                {
                    b.Property<int>("IdCarrinhoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CD_CARRINHO_PRODUTO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCarrinho")
                        .HasColumnName("ID_CARRINHO");

                    b.Property<int>("IdProduto")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<int>("QtdProduto")
                        .HasColumnName("QT_PRODUTO");

                    b.HasKey("IdCarrinhoProduto");

                    b.ToTable("CarrinhoProduto");
                });

            modelBuilder.Entity("Breshop.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CD_PRODUTO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .HasColumnName("NM_CATEGORIA");

                    b.Property<string>("Descricao")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<bool>("EstoqueDisponivel")
                        .HasColumnName("IC_STATUS_PRODUTO");

                    b.Property<string>("Marca")
                        .HasColumnName("NM_MARCA");

                    b.Property<double>("Preco")
                        .HasColumnName("VL_PRODUTO");

                    b.Property<string>("Tamanho")
                        .HasColumnName("DS_TAMANHO");

                    b.Property<string>("UrlImagem")
                        .HasColumnName("DS_URL_IMAGEM");

                    b.HasKey("IdProduto");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Breshop.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CD_USUARIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .HasColumnName("DS_CEP");

                    b.Property<string>("Email")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Endereco")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("Nome")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("Senha")
                        .HasColumnName("DS_SENHA");

                    b.Property<string>("Telefone")
                        .HasColumnName("DS_TELEFONE");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
